package com.gentech.constructoroverload;

class Report {
    Report(String reportId, String reportName, String reportType, String generatedBy) {
        System.out.println("Report ID: " + reportId + " , " + "Report Name: " + reportName + " , " + "Report Type: " + reportType + " , " + "Generated By: " + generatedBy);
    }

    Report(String generationDate, String completionDate) {
        System.out.println("Generation Date: " + generationDate + " , " + "Completion Date: " + completionDate);
    }

    Report(int numberOfPages, int numberOfCharts, int totalDataPoints) {
        System.out.println("Number of Pages: " + numberOfPages + " , " + "Number of Charts: " + numberOfCharts + " , " + "Total Data Points: " + totalDataPoints);
    }
}

public class constructoroverload4 {
    public static void main(String[] args) {
        Report r1 = new Report("RPT123", "Annual Report", "Financial", "Rajesh");

        Report r2 = new Report("20/07/2024", "23/07/2024");

        Report r3 = new Report(50, 10, 5000);
    }
}

